### ISSUE TITLE
Allow all gateways for certain backends

### ISSUE THREAD

**Issue by remydejongjr** [brocaar/chirpstack-packet-multiplexer#15]
Is there easy way to allow all gateways to passthrough to certain hosts/backends ?

**Comment by brocaar** [comment]
At this moment, there is not. If I remember correctly, it starts the UDP sockets on start of the multiplexer service thus in the current architecture it needs to know the Gateway IDs from the start.

**Comment by remydejongjr** [comment]
Hi @brocaar,
Thank you for your quick response sorry to hear that its currently not possible any idea if this will be implemented in the future ?

**Comment by brocaar** [comment]
@remydejongjr,
