### ISSUE TITLE
Wildcard/automatic gateway detection

### ISSUE THREAD

**Issue by darkfader** [brocaar/chirpstack-packet-multiplexer#7]
Can it have some gateway ID wildcard/regexp?
Or are there some other criteria we can match on? (frequency/channel perhaps)
Do we need to restart the service to reload the configuration or can we send some signal?

**Comment by brocaar** [comment]
I do not plan to support freq. / channel filters but I could see an option to forward for all gateway IDs for a given backend useful. Would you be interested in creating a pull-request?

Yes, you do need to restart the service in order to apply configuration changes.

**Comment by darkfader** [comment]
I have to go learn Go first :) I had a small look and probably if I want to implement all my thoughts, I would need to rewrite some structures to dynamically add the gateway IDs. For now, quite busy with other things too.

**Comment by brocaar** [comment]
@darkfader I just pushed a new commit which contains a full rewrite, which allows forwarding for all gateways or configuring a Gateway ID prefix (e.g. `0102030400000000/16`).
