### ISSUE TITLE
Support for gateway alias?

### ISSUE THREAD

**Issue by mfalkvidd** [brocaar/chirpstack-packet-multiplexer#9]
Hi.

One of the LNS we work with requires the Gateway unique identifier to follow a specific format. Due to this, we can't use the real EUI from the LoRa concentrator chip.

I know the real solution would be to fix the broken LNS. But if we were to create a pull request adding support for gateway aliases (translating the Gateway unique identifier when talking to specific backends), is that something you would consider merging, or would you see that as completely outside the scope for the multiplexer?

**Comment by brocaar** [comment]
Hi @mfalkvidd, I can understand the need for this in this specific case, but I would like to keep this outside the scope of the multiplexer to keep it as simple as possible (also to maintain).

**Comment by mfalkvidd** [comment]
Thanks @brocaar , I understand.
